import esbuild from "esbuild";
import { builtinModules } from "node:module";
import process from "process";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
    plugins: [{
        name: 'copy-to-test-vault',
        setup(build) {
            build.onEnd(() => {
                const targetDir = path.join(process.cwd(), 'test-vault', '.obsidian', 'plugins', 'jotback');
                if (!fs.existsSync(targetDir)) {
                    fs.mkdirSync(targetDir, { recursive: true });
                }
                const filesToCopy = ['main.js', 'manifest.json', 'styles.css'];
                filesToCopy.forEach(file => {
                    const src = path.join(process.cwd(), file);
                    const dest = path.join(targetDir, file);
                    if (fs.existsSync(src)) {
                        fs.copyFileSync(src, dest);
                    }
                });
                console.log('Copied build files to test-vault');
            });
        }
    }]
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
