/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MemosPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/view.ts
var import_obsidian = require("obsidian");

// src/utils.ts
function extractTags(content) {
  const regex = /#([\w\u4e00-\u9fff/·]+)/g;
  const matches = content.match(regex);
  if (!matches)
    return [];
  const tags = matches.map((t) => t.substring(1)).filter((t) => t.length > 0 && t.length < 25);
  return [...new Set(tags)];
}
function generateDateString() {
  const date = new Date();
  const pad = (n) => n.toString().padStart(2, "0");
  return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`;
}
function generateFilename() {
  const date = new Date();
  const pad = (n) => n.toString().padStart(2, "0");
  const dateStr = `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`;
  const timeStr = `${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`;
  const ms = date.getMilliseconds().toString().padStart(3, "0");
  return `${dateStr}-${timeStr}-${ms}`;
}
function normalizeLineEndings(text) {
  return text.replace(/\r\n/g, "\n");
}
function parseFrontmatter(content) {
  const normalized = normalizeLineEndings(content);
  if (!normalized.startsWith("---")) {
    return { frontmatterRaw: "", body: normalized, pinned: false, createdAt: null };
  }
  const endIdx = normalized.indexOf("\n---", 3);
  if (endIdx === -1) {
    return { frontmatterRaw: "", body: normalized, pinned: false, createdAt: null };
  }
  const fmText = normalized.substring(3, endIdx);
  const body = normalized.substring(endIdx + 4).trim();
  let pinned = false;
  let createdAt = null;
  const pinnedMatch = fmText.match(/pinned:\s*(true|false)/i);
  if (pinnedMatch) {
    pinned = pinnedMatch[1].toLowerCase() === "true";
  }
  const createdMatch = fmText.match(/created:\s*["']?([^"'\r\n]+)["']?/i);
  if (createdMatch) {
    createdAt = createdMatch[1].trim();
  }
  const frontmatterRaw = normalized.substring(0, endIdx + 4);
  return { frontmatterRaw, body, pinned, createdAt };
}

// src/view.ts
var VIEW_TYPE_MEMOS = "memos-view";
var MemosView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.allTags = /* @__PURE__ */ new Set();
    this.allMemos = [];
    this.isRefreshing = false;
  }
  getViewType() {
    return VIEW_TYPE_MEMOS;
  }
  getDisplayText() {
    return "Memos";
  }
  getIcon() {
    return "edit";
  }
  async refresh() {
    if (this.isRefreshing)
      return;
    this.isRefreshing = true;
    try {
      await this.loadData();
      this.renderList();
    } finally {
      this.isRefreshing = false;
    }
  }
  async onOpen() {
    this.render();
    const isMemoFile = (path) => path.startsWith("memos/");
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (isMemoFile(file.path))
          this.refresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (isMemoFile(file.path))
          this.refresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (isMemoFile(file.path))
          this.refresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        if (isMemoFile(file.path) || isMemoFile(oldPath))
          this.refresh();
      })
    );
  }
  async onClose() {
    this.contentEl.empty();
  }
  async render() {
    const container = this.contentEl;
    container.empty();
    container.addClass("memos-container");
    const composeContainer = container.createDiv({ cls: "compose" });
    const textarea = composeContainer.createEl("textarea", {
      attr: { placeholder: "\u8BB0\u5F55\u4E00\u95EA\u800C\u8FC7\u7684\u7075\u611F..." }
    });
    const footer = composeContainer.createDiv({ cls: "compose-footer" });
    const saveBtn = footer.createEl("button", { cls: "btn-save", text: "\u4FDD\u5B58" });
    const saveMemo = async () => {
      const content = textarea.value.trim();
      if (!content)
        return;
      try {
        await this.createMemo(content);
        textarea.value = "";
        composeContainer.removeClass("has-content");
      } catch (err) {
        console.error("Failed to save memo:", err);
      }
    };
    textarea.addEventListener("input", () => {
      if (textarea.value.trim().length > 0) {
        composeContainer.addClass("has-content");
      } else {
        composeContainer.removeClass("has-content");
      }
    });
    saveBtn.onclick = saveMemo;
    const filterBar = container.createDiv({ cls: "filter-bar" });
    const searchWrap = filterBar.createDiv({ cls: "search-wrap" });
    searchWrap.insertAdjacentHTML("beforeend", `<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>`);
    this.searchInput = searchWrap.createEl("input", {
      cls: "search-input",
      attr: { type: "text", placeholder: "\u641C\u7D22\u5185\u5BB9..." }
    });
    this.tagSelect = filterBar.createEl("select", { cls: "tag-select" });
    this.tagSelect.createEl("option", { value: "", text: "\u6240\u6709\u6807\u7B7E" });
    this.searchInput.addEventListener("input", () => this.renderList());
    this.tagSelect.addEventListener("change", () => this.renderList());
    this.countEl = container.createDiv({ cls: "note-count" });
    this.listContainer = container.createDiv({ cls: "note-list" });
    await this.refresh();
  }
  async createMemo(content) {
    const folderPath = "memos";
    const folder = this.app.vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      try {
        await this.app.vault.createFolder(folderPath);
      } catch (e) {
        console.warn("Folder already exists or error creating folder:", e);
      }
    }
    const filename = generateFilename() + ".md";
    const filepath = `${folderPath}/${filename}`;
    const createdAt = generateDateString();
    const fileContent = `---
created: ${createdAt}
pinned: false
---
${content}`;
    await this.app.vault.create(filepath, fileContent);
  }
  async loadData() {
    const folderPath = "memos";
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(folderPath + "/"));
    const newMemos = [];
    const newTags = /* @__PURE__ */ new Set();
    for (const file of files) {
      const content = await this.app.vault.read(file);
      const parsed = parseFrontmatter(content);
      const body = parsed.body;
      const pinned = parsed.pinned;
      const createdAt = parsed.createdAt || generateDateString();
      const tags = extractTags(body);
      tags.forEach((t) => newTags.add(t));
      newMemos.push({
        file,
        content: body,
        createdAt,
        tags,
        pinned
      });
    }
    newMemos.sort((a, b) => {
      if (a.pinned !== b.pinned)
        return a.pinned ? -1 : 1;
      return b.createdAt.localeCompare(a.createdAt);
    });
    this.allMemos = newMemos;
    this.allTags = newTags;
    const currentSelectedTag = this.tagSelect.value;
    this.tagSelect.innerHTML = '<option value="">\u6240\u6709\u6807\u7B7E</option>';
    Array.from(this.allTags).sort().forEach((tag) => {
      const option = this.tagSelect.createEl("option", { value: tag, text: `#${tag}` });
      if (tag === currentSelectedTag)
        option.selected = true;
    });
  }
  renderList() {
    this.listContainer.empty();
    const query = this.searchInput.value.toLowerCase();
    const selectedTag = this.tagSelect.value;
    const filtered = this.allMemos.filter((memo) => {
      if (selectedTag && !memo.tags.includes(selectedTag))
        return false;
      if (query && !memo.content.toLowerCase().includes(query))
        return false;
      return true;
    });
    this.countEl.textContent = `\u5171 ${filtered.length} \u6761\u7B14\u8BB0`;
    for (const [index, memo] of filtered.entries()) {
      const card = this.listContainer.createDiv({ cls: "note-card" });
      if (memo.pinned)
        card.addClass("pinned");
      const delay = Math.min(index * 35, 200);
      card.style.animationDelay = `${delay}ms`;
      const contentDiv = card.createDiv({ cls: "card-content" });
      import_obsidian.MarkdownRenderer.renderMarkdown(memo.content, contentDiv, memo.file.path, this);
      const footer = card.createDiv({ cls: "card-footer" });
      footer.createDiv({ cls: "card-date", text: memo.createdAt.substring(0, 10) });
      memo.tags.forEach((tag) => {
        const tagEl = footer.createSpan({ cls: "tag-chip", text: `#${tag}` });
        tagEl.onclick = (e) => {
          e.stopPropagation();
          this.tagSelect.value = tag;
          this.renderList();
        };
      });
      card.onclick = (e) => {
        if (e.target.tagName === "A")
          return;
        const leaf = this.app.workspace.getLeaf(false);
        leaf.openFile(memo.file);
      };
    }
  }
};

// src/main.ts
var MemosPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("loading obsidian-memos plugin");
    this.registerView(
      VIEW_TYPE_MEMOS,
      (leaf) => new MemosView(leaf)
    );
    this.addRibbonIcon("edit", "Open Memos", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-memos-view",
      name: "Open Memos",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "open-random-memo",
      name: "Open Random Memo",
      callback: () => {
        this.openRandomMemo();
      }
    });
  }
  async onunload() {
    console.log("unloading obsidian-memos plugin");
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MEMOS);
  }
  async activateView() {
    const { workspace } = this.app;
    const existingLeaves = workspace.getLeavesOfType(VIEW_TYPE_MEMOS);
    if (existingLeaves.length > 0) {
      workspace.revealLeaf(existingLeaves[0]);
      return;
    }
    const leaf = workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_MEMOS, active: true });
    workspace.revealLeaf(leaf);
  }
  async openRandomMemo() {
    const folderPath = "memos";
    const files = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(folderPath + "/"));
    if (files.length === 0)
      return;
    const randomFile = files[Math.floor(Math.random() * files.length)];
    const leaf = this.app.workspace.getLeaf(false);
    await leaf.openFile(randomFile);
  }
};
